# Generated by Django 4.0.6 on 2022-08-02 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='total',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
